title: On Style and Clothing
author: Eric Daub
email: ericdaub@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Deep dives on men's style.

show_excerpts: true # set to false to remove excerpts on the homepage

:theme: minimia
